### ISSUE TITLE
task be killed when visulization

### ISSUE THREAD

**Issue by jonyzhang2023** [huangwl18/geometry-dex#2]
hi huang : 
    thx for your great job on geometry-dex!
    it gives a great inspiration for me.
    i have some problems when i want to make a visulization, and according to termial output i cannot find any reason, i hope you could help me for this.

[](https://github.com/huangwl18/geometry-dex#trained-models)python run_ddpg.py --expID 4 --video_count 1 --n_cycles 40000 --chunk 10 --point_cloud --pointnet_load_path 2 --no_save_buffer --eval --load_path 3

`*** overwriting n_batches from 40 to 3812 ***
adjusted total buffer size from 8.5000e+07 to 1e7
running build_ext

** creating 425 training vec env.. created (time taken: 3.39 s)! **

** creating 570 eval vec env.. created (time taken: 5.47 s)! **

****************************************
** start from loaded checkpoint
****************************************
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/zhangq/anaconda3/envs/geometry-dex-env/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
****************************************
** evaluating over 570 episodes each env over 114 train + test envs
Killed
`

**Comment by huangwl18** [comment]
Thanks for the interest in the project! It doesn't seem like there is an error message in the terminal output you provided (most of it is NumPy warning caused by some incompatibility issue which shouldn't matter). However, visualization typically requires larger memory because of rendering, so the process might be killed because there isn't enough memory. Can you try decreasing the number of parallel envs and see if that works? e.g. try passing in `--num_parallel_envs 85` and `--n_test_rollouts 114`

**Comment by jonyzhang2023** [comment]
Hi Huang:
    It's very kind of you to answer my question about "task be killed when visualization".
    The visualization is very demanding for memory and GPU memory, after more than two weeks of trying I'm still having some problems. Again, I hope you can help me with these questions. : ) 

1. I used an I9 CPU with 16G memory, an Nvidia 1080ti GPU with 11.8G memory. Passing --num_parallel_envs 85, --num_rollouts 85 and --n_test_rollouts 114, the program still be killed without any terminal alerts. Just be killed  T_T . Would you give a minimum requirement to perform visualization about this baseline?
2. I train this baseline on Tesla V100 GPU on remote servers and the results are fantastic! But the RL training part took me almost a week, while pointnet could be trained in just one hour. Is this a normal training time?
3. I noticed that the pointnet in this task only uses 128 points and the outdim is 512 (it turned out great!), which is much less than the origin pointnet. Just curious that Is this streamlined to save training time?
4. When I want to increase the input points num (i add it to 1024), the memory (CPU) keeps growing during training, as if a memory leak has occurred. After a period of time, the program process is killed due to high memory. Do you know why increasing the input points affects the memory requirements?

`== [EXP0008:C244] success %: 0.035, reward: -96.85, dist: 0.589, env time: 18.20 s across 85 episodes
008:244 -- actor/l: 262.404, critic/l: 27.742, steps: 2.082e+06, Cycle FPS: 71.0, train time: 101.19 s -----

== [EXP0008:C245] success %: 0.059, reward: -94.74, dist: 0.529, env time: 15.01 s across 85 episodes
008:245 -- actor/l: 262.043, critic/l: 27.241, steps: 2.091e+06, Cycle FPS: 74.0, train time: 99.72 s -----

== [EXP0008:C246] success %: 0.071, reward: -93.07, dist: 0.477, env time: 15.39 s across 85 episodes
008:246 -- actor/l: 258.819, critic/l: 27.627, steps: 2.100e+06, Cycle FPS: 74.0, train time: 98.67 s -----

Killed
`
Thanks again for your willingness to answer my questions, I keep a lot of dashboard pictures that I recorded during training, I can email them to you if you'd like to check them out. : )

**Comment by huangwl18** [comment]
Please find the answers to your questions below:

1. Perhaps you could try monitoring the memory usage while performing visualization (e.g. calling `free -g` on Linux) and check if this is killed due to insufficient memory. Unfortunately I could not benchmark the code to give a precise minimum requirement. However, the code is constructed to simulate all the objects in parallel (thus `num_parallel_envs==85` for 85 training objects and `n_test_rollouts==114` for 85 training and 29 test objects). Therefore, if it's indeed caused by insufficient memory, you could selectively just visualize a small subset of objects by passing `--test_names <List of Object Names>` and appropriately adjusting `num_parallel_envs` and `n_test_rollouts`.

2. Yes, unfortunately the RL training is slow (partially due to relatively slow simulation speed of MuJoCo and partially due to the incorporation of PointNet).

3. This is not carefully tuned to improve performance or save training time. It is constructed to be the same as the width for the state encoder. So you could certainly try making it smaller to save training time.

4. It is normal that increasing the number of points would increase memory usage, because DDPG keeps a replay buffer for recently experienced transitions (stored in memory), which include point cloud observations.

Hope the answers are helpful!
